

from src.chess_backend_v2.test.test_get_moves import test_get_bishop_psuedo_legal_moves, test_get_king_psuedo_legal_moves, test_get_knight_psuedo_legal_moves, test_get_pawn_psuedo_legal_moves, test_get_rook_psuedo_legal_moves


test_get_pawn_psuedo_legal_moves()
test_get_knight_psuedo_legal_moves()
test_get_bishop_psuedo_legal_moves()
test_get_rook_psuedo_legal_moves()
test_get_king_psuedo_legal_moves()
print("All test succesful")